# Generated by Django 3.0.8 on 2021-05-08 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование отдела.')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя сотрудника.')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия сотрудника.')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество сотрудника.')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта сотрудника.')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт сотрудника')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Division', verbose_name='Отдел сотрудника.')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_head', to='accounts.Employee', verbose_name='Глава отдела.'),
        ),
    ]
