# Generated by Django 3.0.8 on 2021-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество сотрудника.'),
        ),
    ]
