# Generated by Django 3.0.8 on 2021-05-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210508_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Division', verbose_name='Отдел сотрудника.'),
        ),
    ]
