# Generated by Django 3.0.8 on 2021-05-08 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование отдела.')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя сотрудника.')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия сотрудника.')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество сотрудника.')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта сотрудника.')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт сотрудника')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Division', verbose_name='Отдел сотрудника.')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование объекта доступа.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания объекта доступа.')),
                ('DNS_address', models.CharField(max_length=100, null=True, verbose_name='DNS-адрес точки доступа к объекту.')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Описание объекта доступа.')),
                ('location', models.CharField(max_length=100, verbose_name='Расположение объекта доступа.')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_admin', to='home.Employee', verbose_name='Администратор объекта доступа.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_owner', to='home.Employee', verbose_name='Владелец объекта доступа.')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование ресурса.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания ресурса.')),
                ('DNS_address', models.CharField(max_length=100, null=True, verbose_name='DNS-адрес точки доступа к ресурсу.')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Описание ресурса.')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_admin', to='home.Employee', verbose_name='Администратор ресурса.')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Facility', verbose_name='Владелец ресурса.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_owner', to='home.Employee', verbose_name='Владелец ресурса.')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки.')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации (начала работы) заявки.')),
                ('expired_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата деактивации (окончания работы) заявки.')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Статус подтвержденности заявки.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_author', to='home.Employee', verbose_name='Создатель заявки.')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_executor', to='home.Employee', verbose_name='Исполнитель (сотрудник, получающий доступ).')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Resource', verbose_name='Ресурса для предоставления доступа.')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_head', to='home.Employee', verbose_name='Глава отдела.'),
        ),
    ]
