# Generated by Django 3.0.8 on 2021-05-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20210508_1622'),
        ('accounts', '0005_auto_20210508_1622'),
        ('home', '0002_auto_20210508_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approved'), ('DN', 'Denied'), ('AC', 'Active'), ('EX', 'Expired'), ('RC', 'Recalled')], default='PD', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_author', to='accounts.Employee', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_executor', to='accounts.Employee', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='expired_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата деактивации'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата активации'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource', verbose_name='Ресурс'),
        ),
    ]
