# Generated by Django 3.0.8 on 2021-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210508_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='expired_at',
            field=models.DateTimeField(verbose_name='Дата деактивации'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='granted_at',
            field=models.DateTimeField(verbose_name='Дата активации'),
        ),
    ]
