# Generated by Django 3.0.8 on 2021-05-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210508_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[(1, 'Ожидание'), (2, 'Подтверждено'), (3, 'Отказано'), (4, 'Просрочено'), (5, 'Отозвано')], default='PD', max_length=1, verbose_name='Статус'),
        ),
    ]
