# Generated by Django 3.0.8 on 2021-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210509_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('PD', 'Ожидание'), ('AP', 'Подтверждено'), ('DN', 'Отказано'), ('EX', 'Просрочено'), ('RC', 'Отозвано')], default='PD', max_length=2, verbose_name='Статус'),
        ),
    ]
