# Generated by Django 3.0.8 on 2021-05-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210508_1622'),
        ('resources', '0002_auto_20210508_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='DNS_address',
            field=models.CharField(max_length=100, null=True, verbose_name='DNS-адрес точки доступа'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_admin', to='accounts.Employee', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_owner', to='accounts.Employee', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='DNS_address',
            field=models.CharField(max_length=100, null=True, verbose_name='DNS-адрес точки доступа'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_admin', to='accounts.Employee', verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Facility', verbose_name='Объект доступа'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_owner', to='accounts.Employee', verbose_name='Владелец'),
        ),
    ]
